/* tslint:disable */
/* eslint-disable */
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Article
 */
export interface Article {
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    body: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Article
     */
    tagList: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    updatedAt: string;
    /**
     * 
     * @type {boolean}
     * @memberof Article
     */
    favorited: boolean;
    /**
     * 
     * @type {number}
     * @memberof Article
     */
    favoritesCount: number;
    /**
     * 
     * @type {Profile}
     * @memberof Article
     */
    author: Profile;
}
/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    body: string;
    /**
     * 
     * @type {Profile}
     * @memberof Comment
     */
    author: Profile;
}
/**
 * 
 * @export
 * @interface GenericErrorModel
 */
export interface GenericErrorModel {
    /**
     * 
     * @type {GenericErrorModelErrors}
     * @memberof GenericErrorModel
     */
    errors: GenericErrorModelErrors;
}
/**
 * 
 * @export
 * @interface GenericErrorModelErrors
 */
export interface GenericErrorModelErrors {
    /**
     * 
     * @type {Array<string>}
     * @memberof GenericErrorModelErrors
     */
    body: Array<string>;
}
/**
 * 
 * @export
 * @interface LoginUser
 */
export interface LoginUser {
    /**
     * 
     * @type {string}
     * @memberof LoginUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginUser
     */
    password: string;
}
/**
 * 
 * @export
 * @interface LoginUserRequest
 */
export interface LoginUserRequest {
    /**
     * 
     * @type {LoginUser}
     * @memberof LoginUserRequest
     */
    user: LoginUser;
}
/**
 * 
 * @export
 * @interface MultipleArticlesResponse
 */
export interface MultipleArticlesResponse {
    /**
     * 
     * @type {Array<Article>}
     * @memberof MultipleArticlesResponse
     */
    articles: Array<Article>;
    /**
     * 
     * @type {number}
     * @memberof MultipleArticlesResponse
     */
    articlesCount: number;
}
/**
 * 
 * @export
 * @interface MultipleCommentsResponse
 */
export interface MultipleCommentsResponse {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof MultipleCommentsResponse
     */
    comments: Array<Comment>;
}
/**
 * 
 * @export
 * @interface NewArticle
 */
export interface NewArticle {
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    body: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewArticle
     */
    tagList?: Array<string>;
}
/**
 * 
 * @export
 * @interface NewArticleRequest
 */
export interface NewArticleRequest {
    /**
     * 
     * @type {NewArticle}
     * @memberof NewArticleRequest
     */
    article: NewArticle;
}
/**
 * 
 * @export
 * @interface NewComment
 */
export interface NewComment {
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    body: string;
}
/**
 * 
 * @export
 * @interface NewCommentRequest
 */
export interface NewCommentRequest {
    /**
     * 
     * @type {NewComment}
     * @memberof NewCommentRequest
     */
    comment: NewComment;
}
/**
 * 
 * @export
 * @interface NewUser
 */
export interface NewUser {
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    password: string;
}
/**
 * 
 * @export
 * @interface NewUserRequest
 */
export interface NewUserRequest {
    /**
     * 
     * @type {NewUser}
     * @memberof NewUserRequest
     */
    user: NewUser;
}
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    bio: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    image: string;
    /**
     * 
     * @type {boolean}
     * @memberof Profile
     */
    following: boolean;
}
/**
 * 
 * @export
 * @interface ProfileResponse
 */
export interface ProfileResponse {
    /**
     * 
     * @type {Profile}
     * @memberof ProfileResponse
     */
    profile: Profile;
}
/**
 * 
 * @export
 * @interface SingleArticleResponse
 */
export interface SingleArticleResponse {
    /**
     * 
     * @type {Article}
     * @memberof SingleArticleResponse
     */
    article: Article;
}
/**
 * 
 * @export
 * @interface SingleCommentResponse
 */
export interface SingleCommentResponse {
    /**
     * 
     * @type {Comment}
     * @memberof SingleCommentResponse
     */
    comment: Comment;
}
/**
 * 
 * @export
 * @interface TagsResponse
 */
export interface TagsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof TagsResponse
     */
    tags: Array<string>;
}
/**
 * 
 * @export
 * @interface UpdateArticle
 */
export interface UpdateArticle {
    /**
     * 
     * @type {string}
     * @memberof UpdateArticle
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateArticle
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateArticle
     */
    body?: string;
}
/**
 * 
 * @export
 * @interface UpdateArticleRequest
 */
export interface UpdateArticleRequest {
    /**
     * 
     * @type {UpdateArticle}
     * @memberof UpdateArticleRequest
     */
    article: UpdateArticle;
}
/**
 * 
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser {
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    image?: string;
}
/**
 * 
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
    /**
     * 
     * @type {UpdateUser}
     * @memberof UpdateUserRequest
     */
    user: UpdateUser;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    bio: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    image: string;
}
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {User}
     * @memberof UserResponse
     */
    user: User;
}

/**
 * ArticlesApi - axios parameter creator
 * @export
 */
export const ArticlesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create an article. Auth is required
         * @summary Create an article
         * @param {NewArticleRequest} article Article to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createArticle: async (article: NewArticleRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'article' is not null or undefined
            assertParamExists('createArticle', 'article', article)
            const localVarPath = `/articles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(article, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete an article. Auth is required
         * @summary Delete an article
         * @param {string} slug Slug of the article to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteArticle: async (slug: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('deleteArticle', 'slug', slug)
            const localVarPath = `/articles/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get an article. Auth not required
         * @summary Get an article
         * @param {string} slug Slug of the article to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticle: async (slug: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getArticle', 'slug', slug)
            const localVarPath = `/articles/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get most recent articles globally. Use query parameters to filter results. Auth is optional
         * @summary Get recent articles globally
         * @param {string} [tag] Filter by tag
         * @param {string} [author] Filter by author (username)
         * @param {string} [favorited] Filter by favorites of a user (username)
         * @param {number} [limit] Limit number of articles returned (default is 20)
         * @param {number} [offset] Offset/skip number of articles (default is 0)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticles: async (tag?: string, author?: string, favorited?: string, limit?: number, offset?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/articles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tag !== undefined) {
                localVarQueryParameter['tag'] = tag;
            }

            if (author !== undefined) {
                localVarQueryParameter['author'] = author;
            }

            if (favorited !== undefined) {
                localVarQueryParameter['favorited'] = favorited;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get most recent articles from users you follow. Use query parameters to limit. Auth is required
         * @summary Get recent articles from users you follow
         * @param {number} [limit] Limit number of articles returned (default is 20)
         * @param {number} [offset] Offset/skip number of articles (default is 0)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticlesFeed: async (limit?: number, offset?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/articles/feed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an article. Auth is required
         * @summary Update an article
         * @param {string} slug Slug of the article to update
         * @param {UpdateArticleRequest} article Article to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateArticle: async (slug: string, article: UpdateArticleRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('updateArticle', 'slug', slug)
            // verify required parameter 'article' is not null or undefined
            assertParamExists('updateArticle', 'article', article)
            const localVarPath = `/articles/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(article, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ArticlesApi - functional programming interface
 * @export
 */
export const ArticlesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ArticlesApiAxiosParamCreator(configuration)
    return {
        /**
         * Create an article. Auth is required
         * @summary Create an article
         * @param {NewArticleRequest} article Article to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createArticle(article: NewArticleRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SingleArticleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createArticle(article, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete an article. Auth is required
         * @summary Delete an article
         * @param {string} slug Slug of the article to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteArticle(slug: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteArticle(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get an article. Auth not required
         * @summary Get an article
         * @param {string} slug Slug of the article to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArticle(slug: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SingleArticleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getArticle(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get most recent articles globally. Use query parameters to filter results. Auth is optional
         * @summary Get recent articles globally
         * @param {string} [tag] Filter by tag
         * @param {string} [author] Filter by author (username)
         * @param {string} [favorited] Filter by favorites of a user (username)
         * @param {number} [limit] Limit number of articles returned (default is 20)
         * @param {number} [offset] Offset/skip number of articles (default is 0)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArticles(tag?: string, author?: string, favorited?: string, limit?: number, offset?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MultipleArticlesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getArticles(tag, author, favorited, limit, offset, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get most recent articles from users you follow. Use query parameters to limit. Auth is required
         * @summary Get recent articles from users you follow
         * @param {number} [limit] Limit number of articles returned (default is 20)
         * @param {number} [offset] Offset/skip number of articles (default is 0)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArticlesFeed(limit?: number, offset?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MultipleArticlesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getArticlesFeed(limit, offset, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update an article. Auth is required
         * @summary Update an article
         * @param {string} slug Slug of the article to update
         * @param {UpdateArticleRequest} article Article to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateArticle(slug: string, article: UpdateArticleRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SingleArticleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateArticle(slug, article, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ArticlesApi - factory interface
 * @export
 */
export const ArticlesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ArticlesApiFp(configuration)
    return {
        /**
         * Create an article. Auth is required
         * @summary Create an article
         * @param {NewArticleRequest} article Article to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createArticle(article: NewArticleRequest, options?: any): AxiosPromise<SingleArticleResponse> {
            return localVarFp.createArticle(article, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete an article. Auth is required
         * @summary Delete an article
         * @param {string} slug Slug of the article to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteArticle(slug: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteArticle(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * Get an article. Auth not required
         * @summary Get an article
         * @param {string} slug Slug of the article to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticle(slug: string, options?: any): AxiosPromise<SingleArticleResponse> {
            return localVarFp.getArticle(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * Get most recent articles globally. Use query parameters to filter results. Auth is optional
         * @summary Get recent articles globally
         * @param {string} [tag] Filter by tag
         * @param {string} [author] Filter by author (username)
         * @param {string} [favorited] Filter by favorites of a user (username)
         * @param {number} [limit] Limit number of articles returned (default is 20)
         * @param {number} [offset] Offset/skip number of articles (default is 0)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticles(tag?: string, author?: string, favorited?: string, limit?: number, offset?: number, options?: any): AxiosPromise<MultipleArticlesResponse> {
            return localVarFp.getArticles(tag, author, favorited, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Get most recent articles from users you follow. Use query parameters to limit. Auth is required
         * @summary Get recent articles from users you follow
         * @param {number} [limit] Limit number of articles returned (default is 20)
         * @param {number} [offset] Offset/skip number of articles (default is 0)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticlesFeed(limit?: number, offset?: number, options?: any): AxiosPromise<MultipleArticlesResponse> {
            return localVarFp.getArticlesFeed(limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an article. Auth is required
         * @summary Update an article
         * @param {string} slug Slug of the article to update
         * @param {UpdateArticleRequest} article Article to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateArticle(slug: string, article: UpdateArticleRequest, options?: any): AxiosPromise<SingleArticleResponse> {
            return localVarFp.updateArticle(slug, article, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ArticlesApi - object-oriented interface
 * @export
 * @class ArticlesApi
 * @extends {BaseAPI}
 */
export class ArticlesApi extends BaseAPI {
    /**
     * Create an article. Auth is required
     * @summary Create an article
     * @param {NewArticleRequest} article Article to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArticlesApi
     */
    public createArticle(article: NewArticleRequest, options?: any) {
        return ArticlesApiFp(this.configuration).createArticle(article, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete an article. Auth is required
     * @summary Delete an article
     * @param {string} slug Slug of the article to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArticlesApi
     */
    public deleteArticle(slug: string, options?: any) {
        return ArticlesApiFp(this.configuration).deleteArticle(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get an article. Auth not required
     * @summary Get an article
     * @param {string} slug Slug of the article to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArticlesApi
     */
    public getArticle(slug: string, options?: any) {
        return ArticlesApiFp(this.configuration).getArticle(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get most recent articles globally. Use query parameters to filter results. Auth is optional
     * @summary Get recent articles globally
     * @param {string} [tag] Filter by tag
     * @param {string} [author] Filter by author (username)
     * @param {string} [favorited] Filter by favorites of a user (username)
     * @param {number} [limit] Limit number of articles returned (default is 20)
     * @param {number} [offset] Offset/skip number of articles (default is 0)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArticlesApi
     */
    public getArticles(tag?: string, author?: string, favorited?: string, limit?: number, offset?: number, options?: any) {
        return ArticlesApiFp(this.configuration).getArticles(tag, author, favorited, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get most recent articles from users you follow. Use query parameters to limit. Auth is required
     * @summary Get recent articles from users you follow
     * @param {number} [limit] Limit number of articles returned (default is 20)
     * @param {number} [offset] Offset/skip number of articles (default is 0)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArticlesApi
     */
    public getArticlesFeed(limit?: number, offset?: number, options?: any) {
        return ArticlesApiFp(this.configuration).getArticlesFeed(limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an article. Auth is required
     * @summary Update an article
     * @param {string} slug Slug of the article to update
     * @param {UpdateArticleRequest} article Article to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArticlesApi
     */
    public updateArticle(slug: string, article: UpdateArticleRequest, options?: any) {
        return ArticlesApiFp(this.configuration).updateArticle(slug, article, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * CommentsApi - axios parameter creator
 * @export
 */
export const CommentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a comment for an article. Auth is required
         * @summary Create a comment for an article
         * @param {string} slug Slug of the article that you want to create a comment for
         * @param {NewCommentRequest} comment Comment you want to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createArticleComment: async (slug: string, comment: NewCommentRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('createArticleComment', 'slug', slug)
            // verify required parameter 'comment' is not null or undefined
            assertParamExists('createArticleComment', 'comment', comment)
            const localVarPath = `/articles/{slug}/comments`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(comment, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a comment for an article. Auth is required
         * @summary Delete a comment for an article
         * @param {string} slug Slug of the article that you want to delete a comment for
         * @param {number} id ID of the comment you want to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteArticleComment: async (slug: string, id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('deleteArticleComment', 'slug', slug)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteArticleComment', 'id', id)
            const localVarPath = `/articles/{slug}/comments/{id}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the comments for an article. Auth is optional
         * @summary Get comments for an article
         * @param {string} slug Slug of the article that you want to get comments for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleComments: async (slug: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('getArticleComments', 'slug', slug)
            const localVarPath = `/articles/{slug}/comments`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CommentsApi - functional programming interface
 * @export
 */
export const CommentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CommentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a comment for an article. Auth is required
         * @summary Create a comment for an article
         * @param {string} slug Slug of the article that you want to create a comment for
         * @param {NewCommentRequest} comment Comment you want to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createArticleComment(slug: string, comment: NewCommentRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SingleCommentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createArticleComment(slug, comment, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete a comment for an article. Auth is required
         * @summary Delete a comment for an article
         * @param {string} slug Slug of the article that you want to delete a comment for
         * @param {number} id ID of the comment you want to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteArticleComment(slug: string, id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteArticleComment(slug, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get the comments for an article. Auth is optional
         * @summary Get comments for an article
         * @param {string} slug Slug of the article that you want to get comments for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArticleComments(slug: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MultipleCommentsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getArticleComments(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CommentsApi - factory interface
 * @export
 */
export const CommentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CommentsApiFp(configuration)
    return {
        /**
         * Create a comment for an article. Auth is required
         * @summary Create a comment for an article
         * @param {string} slug Slug of the article that you want to create a comment for
         * @param {NewCommentRequest} comment Comment you want to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createArticleComment(slug: string, comment: NewCommentRequest, options?: any): AxiosPromise<SingleCommentResponse> {
            return localVarFp.createArticleComment(slug, comment, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a comment for an article. Auth is required
         * @summary Delete a comment for an article
         * @param {string} slug Slug of the article that you want to delete a comment for
         * @param {number} id ID of the comment you want to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteArticleComment(slug: string, id: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteArticleComment(slug, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the comments for an article. Auth is optional
         * @summary Get comments for an article
         * @param {string} slug Slug of the article that you want to get comments for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleComments(slug: string, options?: any): AxiosPromise<MultipleCommentsResponse> {
            return localVarFp.getArticleComments(slug, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CommentsApi - object-oriented interface
 * @export
 * @class CommentsApi
 * @extends {BaseAPI}
 */
export class CommentsApi extends BaseAPI {
    /**
     * Create a comment for an article. Auth is required
     * @summary Create a comment for an article
     * @param {string} slug Slug of the article that you want to create a comment for
     * @param {NewCommentRequest} comment Comment you want to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public createArticleComment(slug: string, comment: NewCommentRequest, options?: any) {
        return CommentsApiFp(this.configuration).createArticleComment(slug, comment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a comment for an article. Auth is required
     * @summary Delete a comment for an article
     * @param {string} slug Slug of the article that you want to delete a comment for
     * @param {number} id ID of the comment you want to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public deleteArticleComment(slug: string, id: number, options?: any) {
        return CommentsApiFp(this.configuration).deleteArticleComment(slug, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the comments for an article. Auth is optional
     * @summary Get comments for an article
     * @param {string} slug Slug of the article that you want to get comments for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public getArticleComments(slug: string, options?: any) {
        return CommentsApiFp(this.configuration).getArticleComments(slug, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get tags. Auth not required
         * @summary Get tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagsGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/tags`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Get tags. Auth not required
         * @summary Get tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tagsGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TagsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tagsGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Get tags. Auth not required
         * @summary Get tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagsGet(options?: any): AxiosPromise<TagsResponse> {
            return localVarFp.tagsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Get tags. Auth not required
     * @summary Get tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tagsGet(options?: any) {
        return DefaultApiFp(this.configuration).tagsGet(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * FavoritesApi - axios parameter creator
 * @export
 */
export const FavoritesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Favorite an article. Auth is required
         * @summary Favorite an article
         * @param {string} slug Slug of the article that you want to favorite
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createArticleFavorite: async (slug: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('createArticleFavorite', 'slug', slug)
            const localVarPath = `/articles/{slug}/favorite`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unfavorite an article. Auth is required
         * @summary Unfavorite an article
         * @param {string} slug Slug of the article that you want to unfavorite
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteArticleFavorite: async (slug: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('deleteArticleFavorite', 'slug', slug)
            const localVarPath = `/articles/{slug}/favorite`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FavoritesApi - functional programming interface
 * @export
 */
export const FavoritesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FavoritesApiAxiosParamCreator(configuration)
    return {
        /**
         * Favorite an article. Auth is required
         * @summary Favorite an article
         * @param {string} slug Slug of the article that you want to favorite
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createArticleFavorite(slug: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SingleArticleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createArticleFavorite(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Unfavorite an article. Auth is required
         * @summary Unfavorite an article
         * @param {string} slug Slug of the article that you want to unfavorite
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteArticleFavorite(slug: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SingleArticleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteArticleFavorite(slug, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FavoritesApi - factory interface
 * @export
 */
export const FavoritesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FavoritesApiFp(configuration)
    return {
        /**
         * Favorite an article. Auth is required
         * @summary Favorite an article
         * @param {string} slug Slug of the article that you want to favorite
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createArticleFavorite(slug: string, options?: any): AxiosPromise<SingleArticleResponse> {
            return localVarFp.createArticleFavorite(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * Unfavorite an article. Auth is required
         * @summary Unfavorite an article
         * @param {string} slug Slug of the article that you want to unfavorite
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteArticleFavorite(slug: string, options?: any): AxiosPromise<SingleArticleResponse> {
            return localVarFp.deleteArticleFavorite(slug, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FavoritesApi - object-oriented interface
 * @export
 * @class FavoritesApi
 * @extends {BaseAPI}
 */
export class FavoritesApi extends BaseAPI {
    /**
     * Favorite an article. Auth is required
     * @summary Favorite an article
     * @param {string} slug Slug of the article that you want to favorite
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FavoritesApi
     */
    public createArticleFavorite(slug: string, options?: any) {
        return FavoritesApiFp(this.configuration).createArticleFavorite(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unfavorite an article. Auth is required
     * @summary Unfavorite an article
     * @param {string} slug Slug of the article that you want to unfavorite
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FavoritesApi
     */
    public deleteArticleFavorite(slug: string, options?: any) {
        return FavoritesApiFp(this.configuration).deleteArticleFavorite(slug, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * ProfileApi - axios parameter creator
 * @export
 */
export const ProfileApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Follow a user by username
         * @summary Follow a user
         * @param {string} username Username of the profile you want to follow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followUserByUsername: async (username: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('followUserByUsername', 'username', username)
            const localVarPath = `/profiles/{username}/follow`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a profile of a user of the system. Auth is optional
         * @summary Get a profile
         * @param {string} username Username of the profile to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProfileByUsername: async (username: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('getProfileByUsername', 'username', username)
            const localVarPath = `/profiles/{username}`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unfollow a user by username
         * @summary Unfollow a user
         * @param {string} username Username of the profile you want to unfollow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unfollowUserByUsername: async (username: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('unfollowUserByUsername', 'username', username)
            const localVarPath = `/profiles/{username}/follow`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProfileApi - functional programming interface
 * @export
 */
export const ProfileApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProfileApiAxiosParamCreator(configuration)
    return {
        /**
         * Follow a user by username
         * @summary Follow a user
         * @param {string} username Username of the profile you want to follow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async followUserByUsername(username: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.followUserByUsername(username, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get a profile of a user of the system. Auth is optional
         * @summary Get a profile
         * @param {string} username Username of the profile to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProfileByUsername(username: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProfileByUsername(username, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Unfollow a user by username
         * @summary Unfollow a user
         * @param {string} username Username of the profile you want to unfollow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unfollowUserByUsername(username: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unfollowUserByUsername(username, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ProfileApi - factory interface
 * @export
 */
export const ProfileApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProfileApiFp(configuration)
    return {
        /**
         * Follow a user by username
         * @summary Follow a user
         * @param {string} username Username of the profile you want to follow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followUserByUsername(username: string, options?: any): AxiosPromise<ProfileResponse> {
            return localVarFp.followUserByUsername(username, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a profile of a user of the system. Auth is optional
         * @summary Get a profile
         * @param {string} username Username of the profile to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProfileByUsername(username: string, options?: any): AxiosPromise<ProfileResponse> {
            return localVarFp.getProfileByUsername(username, options).then((request) => request(axios, basePath));
        },
        /**
         * Unfollow a user by username
         * @summary Unfollow a user
         * @param {string} username Username of the profile you want to unfollow
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unfollowUserByUsername(username: string, options?: any): AxiosPromise<ProfileResponse> {
            return localVarFp.unfollowUserByUsername(username, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProfileApi - object-oriented interface
 * @export
 * @class ProfileApi
 * @extends {BaseAPI}
 */
export class ProfileApi extends BaseAPI {
    /**
     * Follow a user by username
     * @summary Follow a user
     * @param {string} username Username of the profile you want to follow
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileApi
     */
    public followUserByUsername(username: string, options?: any) {
        return ProfileApiFp(this.configuration).followUserByUsername(username, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a profile of a user of the system. Auth is optional
     * @summary Get a profile
     * @param {string} username Username of the profile to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileApi
     */
    public getProfileByUsername(username: string, options?: any) {
        return ProfileApiFp(this.configuration).getProfileByUsername(username, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unfollow a user by username
     * @summary Unfollow a user
     * @param {string} username Username of the profile you want to unfollow
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileApi
     */
    public unfollowUserByUsername(username: string, options?: any) {
        return ProfileApiFp(this.configuration).unfollowUserByUsername(username, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UserAndAuthenticationApi - axios parameter creator
 * @export
 */
export const UserAndAuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Register a new user
         * @summary Register a new user
         * @param {NewUserRequest} body Details of the new user to register
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (body: NewUserRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('createUser', 'body', body)
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the currently logged-in user
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Login for existing user
         * @summary Existing user login
         * @param {LoginUserRequest} body Credentials to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (body: LoginUserRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('login', 'body', body)
            const localVarPath = `/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updated user information for current user
         * @summary Update current user
         * @param {UpdateUserRequest} body User details to update. At least **one** field is required.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCurrentUser: async (body: UpdateUserRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('updateCurrentUser', 'body', body)
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserAndAuthenticationApi - functional programming interface
 * @export
 */
export const UserAndAuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserAndAuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Register a new user
         * @summary Register a new user
         * @param {NewUserRequest} body Details of the new user to register
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(body: NewUserRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Gets the currently logged-in user
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUser(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Login for existing user
         * @summary Existing user login
         * @param {LoginUserRequest} body Credentials to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(body: LoginUserRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Updated user information for current user
         * @summary Update current user
         * @param {UpdateUserRequest} body User details to update. At least **one** field is required.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCurrentUser(body: UpdateUserRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCurrentUser(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserAndAuthenticationApi - factory interface
 * @export
 */
export const UserAndAuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserAndAuthenticationApiFp(configuration)
    return {
        /**
         * Register a new user
         * @summary Register a new user
         * @param {NewUserRequest} body Details of the new user to register
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(body: NewUserRequest, options?: any): AxiosPromise<UserResponse> {
            return localVarFp.createUser(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the currently logged-in user
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: any): AxiosPromise<UserResponse> {
            return localVarFp.getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * Login for existing user
         * @summary Existing user login
         * @param {LoginUserRequest} body Credentials to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(body: LoginUserRequest, options?: any): AxiosPromise<UserResponse> {
            return localVarFp.login(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Updated user information for current user
         * @summary Update current user
         * @param {UpdateUserRequest} body User details to update. At least **one** field is required.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCurrentUser(body: UpdateUserRequest, options?: any): AxiosPromise<UserResponse> {
            return localVarFp.updateCurrentUser(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserAndAuthenticationApi - object-oriented interface
 * @export
 * @class UserAndAuthenticationApi
 * @extends {BaseAPI}
 */
export class UserAndAuthenticationApi extends BaseAPI {
    /**
     * Register a new user
     * @summary Register a new user
     * @param {NewUserRequest} body Details of the new user to register
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAndAuthenticationApi
     */
    public createUser(body: NewUserRequest, options?: any) {
        return UserAndAuthenticationApiFp(this.configuration).createUser(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the currently logged-in user
     * @summary Get current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAndAuthenticationApi
     */
    public getCurrentUser(options?: any) {
        return UserAndAuthenticationApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Login for existing user
     * @summary Existing user login
     * @param {LoginUserRequest} body Credentials to use
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAndAuthenticationApi
     */
    public login(body: LoginUserRequest, options?: any) {
        return UserAndAuthenticationApiFp(this.configuration).login(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updated user information for current user
     * @summary Update current user
     * @param {UpdateUserRequest} body User details to update. At least **one** field is required.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAndAuthenticationApi
     */
    public updateCurrentUser(body: UpdateUserRequest, options?: any) {
        return UserAndAuthenticationApiFp(this.configuration).updateCurrentUser(body, options).then((request) => request(this.axios, this.basePath));
    }
}


